"""The /chat endpoint.

We stream the reply using Server-Sent Events (SSE). Streaming matters because a
full LLM answer can take several seconds; sending it word-by-word makes the UI
feel instant instead of frozen.

SSE wire format: each event is a line beginning with "data: " followed by the
payload and a blank line. We send small JSON objects so the frontend can tell a
normal text chunk apart from the "done" signal or an error.
"""

import json
from collections.abc import Iterator

from fastapi import APIRouter
from fastapi.responses import StreamingResponse

from models import ChatRequest
from services.gemini import stream_chat

router = APIRouter()


def _sse(data: dict) -> str:
    """
    Convert a Python dictionary into a Server-Sent Events (SSE) message.

    The dictionary is serialized to JSON and prefixed with the ``data:`` field
    as required by the SSE specification. Each event is terminated with two
    newline characters to indicate the end of the event.

    Args:
        data (dict): The payload to send to the client.

    Returns:
        str: A properly formatted SSE event string.

    Example:
        >>> _sse({"type": "chunk", "content": "Hello"})
        'data: {"type": "chunk", "content": "Hello"}\\n\\n'
    """
    return f"data: {json.dumps(data)}\n\n"


@router.post("/chat")
def chat(request: ChatRequest) -> StreamingResponse:
    """
    Stream AI-generated chat responses to the client using Server-Sent Events.

    This endpoint accepts a chat request containing the conversation history,
    generates the assistant's response incrementally via ``stream_chat()``, and
    streams each generated chunk to the client as an SSE event.

    Event Types:
        - ``chunk``: A partial response generated by the model.
        - ``done``: Indicates that the response has completed successfully.
        - ``error``: Indicates an exception occurred while generating the
          response. The error message is included in the event payload.

    Args:
        request (ChatRequest): The incoming chat request containing the
            conversation messages.

    Returns:
        StreamingResponse: A streaming HTTP response with media type
        ``text/event-stream`` that emits SSE events until completion or error.
    """
    def event_stream() -> Iterator[str]:
        try:
            for piece in stream_chat(request.messages):
                yield _sse({"type": "chunk", "content": piece})
            yield _sse({"type": "done"})
        except Exception as exc:  # surface the error to the UI instead of hanging
            yield _sse({"type": "error", "content": str(exc)})

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )
